### ISSUE TITLE
运行rkllm的ekllm_api_demo报错../sysdeps/unix/sysv/linux/wait4.c: 没有那个文件或目录.

### ISSUE THREAD

**Issue by secreat14** [airockchip/rknn-llm#124]
Failed to open file for reading: robot: :0: GGML_ASSERT(view_src == NULL || data_size == 0 || data_size + view_offs <= ggml_nbytes(view_src)) failed
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
0x0000ffff9fc467b4 in __GI___wait4 (pid=10653, stat_loc=0xffffc1cec45c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: 没有那个文件或目录.
#0  0x0000ffff9fc467b4 in __GI___wait4 (pid=10653, stat_loc=0xffffc1cec45c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x0000ffffa0189464 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#2  0x0000ffffa01a82a8 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#3  0x0000ffffa00d6454 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#4  0x0000ffffa00d923c in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#5  0x0000ffffa013a5f8 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#6  0x0000ffffa00deb08 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#7  0x0000ffffa00ee774 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#8  0x0000ffffa006bc08 in ?? () from /root/rknn-llm/rkllm-runtime/examples/rkllm_api_demo/../../runtime/Linux/librkllm_api/aarch64/librkllmrt.so
#9  0x0000aaaac86527ec in main ()

**Comment by secreat14** [comment]
我在运行rkllm 1.1.2时出现了一以上报错，请问有什么解决方案吗？是我的环境问题还是代码问题
